# Generated by Django 4.1.5 on 2023-01-31 16:22

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=25)),
                ('login_pass', django_cryptography.fields.encrypt(models.CharField(max_length=25))),
                ('member1', models.CharField(max_length=40)),
                ('member2', models.CharField(max_length=40)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
