# Generated by Django 4.1.5 on 2023-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_gender1_team_gender2_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='login_pass',
            field=models.CharField(max_length=25),
        ),
    ]
