# Generated by Django 4.1.5 on 2023-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_file_alter_team_login_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
