# Generated by Django 4.1.5 on 2023-02-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='file',
        ),
    ]
