# Generated by Django 4.1.5 on 2023-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_img_team_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='file',
        ),
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.ImageField(default='img.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
