# Generated by Django 4.1.5 on 2023-02-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_remove_team_file_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.CharField(default='user', max_length=25),
            preserve_default=False,
        ),
    ]
